#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any command fails
set -o errexit

KEYCLOAK_VERSION="16.1.0"
MYSQLJ_VERSION="8.0.27"

echo "* Setup keycloak env"
groupadd -g 1110 keycloak
useradd -m -s /usr/bin/bash -d /opt/keycloak -u 1100 -g keycloak keycloak
passwd -N keycloak
passwd -d keycloak

cd /opt/keycloak
# https://www.keycloak.org/downloads
curl -LO https://download.qutic.com/src/keycloak/keycloak-${KEYCLOAK_VERSION}.tar.gz
gtar xf keycloak-${KEYCLOAK_VERSION}.tar.gz
rm keycloak-${KEYCLOAK_VERSION}.tar.gz
ln -nfs keycloak-${KEYCLOAK_VERSION} keycloak

echo "* Setup keycloak mysql"
mkdir -p /opt/keycloak/keycloak/modules/system/layers/keycloak/com/mysql/main
cd /opt/keycloak/keycloak/modules/system/layers/keycloak/com/mysql/main
# https://dev.mysql.com/downloads/connector/j/
curl -LO https://download.qutic.com/src/keycloak/mysql-connector-java-${MYSQLJ_VERSION}.tar.gz
gtar xf mysql-connector-java-${MYSQLJ_VERSION}.tar.gz
mv mysql-connector-java-${MYSQLJ_VERSION}/mysql-connector-java-${MYSQLJ_VERSION}.jar .
rm -rf mysql-connector-java-${MYSQLJ_VERSION}
rm mysql-connector-java-${MYSQLJ_VERSION}.tar.gz
cat >> module.xml << EOF
<?xml version="1.0" ?>
<module xmlns="urn:jboss:module:1.3" name="com.mysql">
 <resources>
  <resource-root path="mysql-connector-java-${MYSQLJ_VERSION}.jar" />
 </resources>
 <dependencies>
  <module name="javax.api"/>
  <module name="javax.transaction.api"/>
 </dependencies>
</module>
EOF
mv /opt/keycloak/keycloak/standalone/configuration/standalone.xml /opt/keycloak/keycloak/standalone/configuration/standalone.xml.bak
mv /var/tmp/standalone.xml /opt/keycloak/keycloak/standalone/configuration/standalone.xml

chown -R keycloak:keycloak /opt/keycloak

# Clean up
echo "* Cleaning up."
rm /root/customize

# Prepare image for provisioning
sm-prepare-image -y
